// <auto-generated />
using System;
using AutoDealer.DAL.Database;
using AutoDealer.DAL.Database.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoDealer.DAL.Migrations
{
    [DbContext(typeof(AutoDealerContext))]
    [Migration("20230303140000_UpdateTriggersAndRemoveAssemblyAutoFunction")]
    partial class UpdateTriggersAndRemoveAssemblyAutoFunction
    {
    }
}
