version: "1"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./AutoDealer.API/Dockerfile
    environment:
      CONNECTIONSTRINGS__DEFAULT: User ID=postgres;Password=password;Host=db;Port=5432;Database=autodealer
    links:
      - pgsql
  
  pgsql:
    container_name: db
    restart: always
    image: postgres
    ports:
      - 54545:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: autodealer