version: "1"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./AutoDealer.API/Dockerfile
    environment:
      CONNECTIONSTRINGS__DEFAULT: Host=db; Port=5432; Database=autodealer; User ID=postgres; Password=password
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: https://*:44357
    ports:
      - 4444:44357
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ./api.pfx:/root/.aspnet/https/api.pfx:ro
    links:
      - pgsql

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./AutoDealer.Web/Dockerfile
    environment:
      CONNECTIONSTRINGS__DEFAULT: Host=db; Port=5432; Database=autodealer; User ID=postgres; Password=password
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: https://*:44388
    ports:
      - 8888:44388
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ./web.pfx:/root/.aspnet/https/web.pfx:ro
    links:
      - api

  pgsql:
    container_name: db
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: autodealer
    ports:
      - 5454:5432
